#!/bin/sh

set -e

scriptdir=$(cd $(dirname $0) && pwd)
fwdir=$scriptdir/../../../contrib/dev/drm2/radeonkmsfw

for file in $fwdir/*.uu; do
	img=$(basename $file)
	img=${img%.bin.uu}
	echo "Image: $img"

	mkdir -p $scriptdir/$img
	cat > $scriptdir/$img/Makefile <<EOF
# \$FreeBSD$

KMOD=	radeonkmsfw_$img
IMG=	$img

.include <bsd.kmod.mk>
EOF
done
